# info:
info:
  application:
    name: PagoPA API - Reporting Organizations Enrollments
    artifactId: ReportingOrgsEnrollment
    version: 0.0.1
  properties:
    environment: ${ENV}
---
# micronaut settings:
micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
---
#tag::datasource_table
tables:
  reporting:
    connection: ${STORAGE_PRIMARY_CONNECTION_KEY}
    organizations:
      table: ${ORGANIZATIONS_TABLE}
#end::datasource_table
---
#tag::datasource_sql[]
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
#end::datasource_sql[]
---
#tag::jpa[]
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
#end::jpa[]
---
#tag::netty[]
netty:
  default:
    allocator:
      max-order: 3
#end::netty[]
