# azure-pipelines.yml
trigger: none

pool:
  name: performance-test-linux

parameters:
  - name: "ENVIRONMENT"
    displayName: "Environment"
    type: string
    values:
      - "dev"
      - "uat"
  - name: "TEST_TYPE"
    displayName: "Test type"
    type: string
    values:
      - "load"
      - "spike"
      - "stress"
      - "smoke"
  - name: "SCRIPT"
    displayName: "Script name"
    type: string
    values:
      - create_organization
      - delete_organization
      - get_organization
      - get_organizations

variables:
  ${{ if eq(parameters['ENVIRONMENT'], 'dev') }}:
    orgEnrollmentSubscriptionKey: '$(DEV_POC_ENROLLMENT_SUB_KEY)'
  ${{ if eq(parameters['ENVIRONMENT'], 'uat') }}:
    orgEnrollmentSubscriptionKey: '$(DEV_POC_ENROLLMENT_SUB_KEY)'

steps:
  - script: |
      cd ./performance-tests/src
      docker pull grafana/k6
    displayName: Pull k6 image

  - script: |
      docker run \
        -v ${PWD}:/script \
        -e ORG_ENROLLMENT_SUBSCRIPTION_KEY=$(orgEnrollmentSubscriptionKey) \
        -e VARS=${{ parameters.ENVIRONMENT }}.environment.json \
        -e TEST_TYPE=./test-types/${{ parameters.TEST_TYPE }}.json \
        grafana/k6 run /script/${{ parameters.SCRIPT }}.js \
    displayName: Run k6 ${{ parameters.SCRIPT }} on ${{ parameters.ENVIRONMENT }}
